project:
  type: website

website:
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - drinks.qmd
      - savory.qmd
      - sweet.qmd

format:
  html:
    theme: cosmo
    css:
      - https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css